name: ASCII cow Workflow

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install -y cowsay

      - name: Execute Cowsay CMD
        run: cowsay "Run for cover, I am a cow....RAWR" >> cow.txt


      - name: Test File Exists
        run: grep -i "cow" cow.txt

      - name: Read File
        run: cat cow.txt

      - name: List Repo Files
        run: ls -ltra



  

      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md
