name: Exploring Variables and Secrets

on:
  workflow_dispatch:
  # push:

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: siddharth1346
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    concurrency:
      group: production-deployement
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Container
        timeout-minutes: 1
        run: |
          docker run -dp 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 600
